const sidebars = {
  aboutSidebar: [{ type: 'autogenerated', dirName: 'about' }],
  experienceSidebar: [{ type: 'autogenerated', dirName: 'experience' }],
  skillsSidebar: [{ type: 'autogenerated', dirName: 'skills' }],
  learningsSidebar: [{ type: 'autogenerated', dirName: 'learnings' }],
  achievementsSidebar: [{ type: 'autogenerated', dirName: 'achievements' }],
  letsConnectSidebar: [{ type: 'autogenerated', dirName: 'lets-connect' }],
};

module.exports = sidebars;
