const sidebars = {
  aboutSidebar: [{ type: 'autogenerated', dirName: 'about' }],
  experienceSidebar: [{ type: 'autogenerated', dirName: 'experience' }],
  skillsSidebar: [{ type: 'autogenerated', dirName: 'skills' }],
  coursesSidebar: [{ type: 'autogenerated', dirName: 'courses' }],
  achievementsSidebar: [{ type: 'autogenerated', dirName: 'achievements' }],
  contactMeSidebar: [{ type: 'autogenerated', dirName: 'contact-me' }],
};

module.exports = sidebars;
